### ISSUE TITLE
`canvas` elements not removed from DOM after component with the grid is unmounted

### ISSUE THREAD

**Issue by romanstetsyk** [quicktype/glide-data-grid#711]
When using the grid component in my application, I noticed that the `canvas` elements used by the grid are not being properly removed from the DOM when the component is unmounted. This behavior leads to a buildup of canvas elements in the DOM.

Steps to Reproduce:
[Link to the codesandbox](https://codesandbox.io/p/sandbox/vigilant-golick-mcrn7o)

Screen recording:

https://github.com/glideapps/glide-data-grid/assets/25715951/bb4dfefb-f411-442d-8cc0-45a54a340abb

**Comment by pzcfg** [comment]
I think I found the canvas that wasn't being cleaned up properly. The fix is in #717

---

# Before: Canvases being left behind with each Show/Hide

https://github.com/glideapps/glide-data-grid/assets/94077014/57e74d4a-0b98-4b4c-b918-1e0ccc45f633

# After: All canvases are cleaned up after each Show/Hide

https://github.com/glideapps/glide-data-grid/assets/94077014/78c5e04f-a07e-4bae-a411-faa728ae3317
