### ISSUE TITLE
@glideapps/glide-data-grid-cells `useExtraCells` not exporting methods

### ISSUE THREAD

**Issue by bruceharrison1984** [quicktype/glide-data-grid#768]
I'm trying to make use of the `@glideapps/glide-data-grid-cells` package to create a link cell. Upon import the `useExtraCells` function, I found that the `drawCell` and `provideEditor` methods don't appear to be exported.

![image](https://github.com/quicktype/glide-data-grid/assets/17836372/8c6181d1-0f9e-419a-9177-533774baa527)

**Comment by jassmith** [comment]
Sorry wherever you are seeing those docs is using the old API. We simplified the API so there are just customRenderers for each cell. You just pass them into the customRenderers property of your data grid and they will start working. You can literally do:

```
<DataEditor {...useExtraCells()} />
```

and it will work. I wouldn't do it that way because ew, but ya know, it shows the concept.

**Comment by jassmith** [comment]
Also if you could tell me where I forgot to update, probably somewhere super obvious like the README... I will fix it

**Comment by bruceharrison1984** [comment]
It actually was in the README for `@glideapps/glide-data-grid-cells` 😆 

https://www.npmjs.com/package/@glideapps/glide-data-grid-cells
